=== Franjimlop/champions/champions.dtd
<!ELEMENT competicion (jornada+)>
<!ATTLIST competicion nombre CDATA #REQUIRED>
<!ATTLIST competicion temporada CDATA #REQUIRED>
    <!ELEMENT jornada (partido+)>
    <!ATTLIST jornada identificador CDATA #REQUIRED>
        <!ELEMENT partido (local, goleslocal, golesvisitante, visitante, estadio)>
        <!ATTLIST partido fecha CDATA #REQUIRED>
        <!ATTLIST partido hora CDATA #REQUIRED>
        <!ATTLIST partido arbitro CDATA #REQUIRED>
        <!ATTLIST partido grupo CDATA #IMPLIED>
            <!ELEMENT local (#PCDATA)>
                <!ATTLIST local escudo CDATA #REQUIRED>
            <!ELEMENT goleslocal (#PCDATA)>
            <!ELEMENT golesvisitante (#PCDATA)>
            <!ELEMENT visitante (#PCDATA)>
                <!ATTLIST visitante escudo CDATA #REQUIRED>
            <!ELEMENT estadio (#PCDATA)>

=== Franjimlop/champions/champions.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE competicion SYSTEM "champions.dtd">
<?xml-stylesheet href="style.xsl" type="text/xsl"?>

<competicion nombre="UEFA Champions League" temporada="2021/2022">
    <jornada identificador="Fase de grupos Jornada 1">
        <partido fecha="14/09/2021" hora="18:45" arbitro="Aleksei Kulbakov">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/52714.png">Sevilla</local>
            <goleslocal>1</goleslocal>
            <golesvisitante>1</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50030.png">Salzburg</visitante>
            <estadio>Estadio Ramón Sánchez-Pizjuán</estadio>
        </partido>
        <partido fecha="14/09/2021" hora="18:45" arbitro="François Letexier">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50031.png">Young Boys</local>
            <goleslocal>2</goleslocal>
            <golesvisitante>1</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/52682.png">Man. United</visitante>
            <estadio>Stadion Wankdorf</estadio>
        </partido>
        <partido fecha="14/09/2021" hora="21:00" arbitro="Clément Turpin">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/70691.png">Villarreal</local>
            <goleslocal>2</goleslocal>
            <golesvisitante>2</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/52816.png">Atalanta</visitante>
            <estadio>Estadio de la Cerámica</estadio>
        </partido>
        <partido fecha="14/09/2021" hora="21:00" arbitro="Bartosz Frankowski">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/52914.png">Chelsea</local>
            <goleslocal>1</goleslocal>
            <golesvisitante>0</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/52826.png">Zenit</visitante>
            <estadio>Stamford Bridge</estadio>
        </partido>
        <partido fecha="14/09/2021" hora="21:00" arbitro="Artur Dias">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50152.png">Malmö</local>
            <goleslocal>0</goleslocal>
            <golesvisitante>3</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50139.png">Juventus</visitante>
            <estadio>Malmö New Stadium</estadio>
        </partido>
        <partido fecha="14/09/2021" hora="21:00" arbitro="Danny Makkelie">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/75797.png">LOSC</local>
            <goleslocal>0</goleslocal>
            <golesvisitante>0</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/64332.png">Wolfsburg</visitante>
            <estadio>Stade Pierre Mauroy</estadio>
        </partido>
        <partido fecha="14/09/2021" hora="21:00" arbitro="Michael Oliver">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50080.png">Barcelona</local>
            <goleslocal>0</goleslocal>
            <golesvisitante>3</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50037.png">Bayern</visitante>
            <estadio>Camp Nou</estadio>
        </partido>
        <partido fecha="14/09/2021" hora="21:00" arbitro="Anthony Taylor">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/52723.png">Dynamo Kyiv</local>
            <goleslocal>0</goleslocal>
            <golesvisitante>0</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50147.png">Benfica</visitante>
            <estadio>NSC Olimpiyskiy</estadio>
        </partido>
        <partido fecha="15/09/2021" hora="18:45" arbitro="Antonio Mateu Lahoz">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50157.png">Beşiktaş</local>
            <goleslocal>1</goleslocal>
            <golesvisitante>2</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/52758.png">Dortmund</visitante>
            <estadio>Beşiktaş Park</estadio>
        </partido>
        <partido fecha="15/09/2021" hora="18:45" arbitro="Deniz Aytekin">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/69606.png">Sheriff</local>
            <goleslocal>2</goleslocal>
            <golesvisitante>0</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/52707.png">Shakhtar Donetsk</visitante>
            <estadio>Sheriff Stadion</estadio>
        </partido>
        <partido fecha="15/09/2021" hora="21:00" arbitro="Daniel Siebert">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50138.png">Inter</local>
            <goleslocal>0</goleslocal>
            <golesvisitante>1</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50051.png">Real Madrid</visitante>
            <estadio>Stadio San Siro</estadio>
        </partido>
        <partido fecha="15/09/2021" hora="21:00" arbitro="Szymon Marciniak">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/7889.png">Liverpool</local>
            <goleslocal>3</goleslocal>
            <golesvisitante>2</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/100x100/50058.png">Milan</visitante>
            <estadio>Anfield</estadio>
        </partido>
        <partido fecha="15/09/2021" hora="21:00" arbitro="Serdar Gözübüyük">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/52919.png">Man. City</local>
            <goleslocal>6</goleslocal>
            <golesvisitante>3</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/2603790.png">Leipzig</visitante>
            <estadio>City of Manchester Stadium</estadio>
        </partido>
        <partido fecha="15/09/2021" hora="21:00" arbitro="Sandro Schärer">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50043.png">Club Brugge</local>
            <goleslocal>1</goleslocal>
            <golesvisitante>1</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/52747.png">Paris</visitante>
            <estadio>Jan Breydelstadion</estadio>
        </partido>
        <partido fecha="15/09/2021" hora="21:00" arbitro="Ovidiu Haţegan">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50124.png">Atlético</local>
            <goleslocal>0</goleslocal>
            <golesvisitante>0</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50064.png">Porto</visitante>
            <estadio>Estadio Metropolitano</estadio>
        </partido>
        <partido fecha="15/09/2021" hora="21:00" arbitro="José María Sánchez">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50149.png">Sporting CP</local>
            <goleslocal>1</goleslocal>
            <golesvisitante>5</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50143.png">Ajax</visitante>
            <estadio>Estádio José Alvalade</estadio>
        </partido>
    </jornada>
    <jornada identificador="Fase de grupos Jornada 2">
        <partido fecha="28/09/2021" hora="18:45" arbitro="Benoît Bastien">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50143.png">Ajax</local>
            <goleslocal>2</goleslocal>
            <golesvisitante>0</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50157.png">Beşiktaş</visitante>
            <estadio>Johan Cruijff Arena</estadio>
        </partido>
        <partido fecha="28/09/2021" hora="18:45" arbitro="István Kovács">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/52707.png">Shakhtar Donetsk</local>
            <goleslocal>0</goleslocal>
            <golesvisitante>0</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50138.png">Inter</visitante>
            <estadio>NSC Olimpiyskiy</estadio>
        </partido>
        <partido fecha="28/09/2021" hora="21:00" arbitro="Cüneyt Çakır">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/100x100/50058.png">Milan</local>
            <goleslocal>1</goleslocal>
            <golesvisitante>2</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50124.png">Atlético</visitante>
            <estadio>Stadio San Siro</estadio>
        </partido>
        <partido fecha="28/09/2021" hora="21:00" arbitro="Slavko Vinčić">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/2603790.png">Leipzig</local>
            <goleslocal>1</goleslocal>
            <golesvisitante>2</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50043.png">Club Brugge</visitante>
            <estadio>RB Arena</estadio>
        </partido>
        <partido fecha="28/09/2021" hora="21:00" arbitro="Sergei Karasev">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50064.png">Porto</local>
            <goleslocal>1</goleslocal>
            <golesvisitante>5</golesvisitante>
            <visitante escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/7889.png">Liverpool</visitante>
            <estadio>Estádio do Dragão</estadio>
        </partido>
        <partido fecha="28/09/2021" hora="21:00" arbitro="Lawrence Visser">
            <local escudo="https://img.uefa.com/imgml/TP/teams/logos/64x64/50051.png">Real Madrid</local>
            <goleslocal>1</goleslocal>
            <golesvisitante>2</golesvisitante>
